#if !defined(AFX_MFTPOSITION_H__40CBA677_5AF5_4DCA_95C7_BF869B81878E__INCLUDED_)
#define AFX_MFTPOSITION_H__40CBA677_5AF5_4DCA_95C7_BF869B81878E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMFTPosition wrapper class

class CMFTPosition : public CWnd
{
protected:
	DECLARE_DYNCREATE(CMFTPosition)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xfc774eea, 0x372a, 0x4b70, { 0x90, 0x5f, 0x7, 0xb9, 0xec, 0x87, 0x29, 0x8a } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetReadyState();
	float GetMinPos();
	void SetMinPos(float);
	float GetMaxPos();
	void SetMaxPos(float);
	float GetCurPos();
	void SetCurPos(float);
	BOOL GetValve1Open();
	void SetValve1Open(BOOL);
	BOOL GetValve2Open();
	void SetValve2Open(BOOL);

// Operations
public:
	void DrawAll();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MFTPOSITION_H__40CBA677_5AF5_4DCA_95C7_BF869B81878E__INCLUDED_)
