// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "mftposition.h"

/////////////////////////////////////////////////////////////////////////////
// CMFTPosition

IMPLEMENT_DYNCREATE(CMFTPosition, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CMFTPosition properties

long CMFTPosition::GetReadyState()
{
	long result;
	GetProperty(DISPID_READYSTATE, VT_I4, (void*)&result);
	return result;
}

float CMFTPosition::GetMinPos()
{
	float result;
	GetProperty(0x1, VT_R4, (void*)&result);
	return result;
}

void CMFTPosition::SetMinPos(float propVal)
{
	SetProperty(0x1, VT_R4, propVal);
}

float CMFTPosition::GetMaxPos()
{
	float result;
	GetProperty(0x2, VT_R4, (void*)&result);
	return result;
}

void CMFTPosition::SetMaxPos(float propVal)
{
	SetProperty(0x2, VT_R4, propVal);
}

float CMFTPosition::GetCurPos()
{
	float result;
	GetProperty(0x3, VT_R4, (void*)&result);
	return result;
}

void CMFTPosition::SetCurPos(float propVal)
{
	SetProperty(0x3, VT_R4, propVal);
}

BOOL CMFTPosition::GetValve1Open()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CMFTPosition::SetValve1Open(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

BOOL CMFTPosition::GetValve2Open()
{
	BOOL result;
	GetProperty(0x5, VT_BOOL, (void*)&result);
	return result;
}

void CMFTPosition::SetValve2Open(BOOL propVal)
{
	SetProperty(0x5, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CMFTPosition operations

void CMFTPosition::DrawAll()
{
	InvokeHelper(0x6, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CMFTPosition::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
